# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

with open('подсказка.txt', 'r', encoding='utf-8') as ptext:
    text = ''
    for i in ptext.readlines():
        text += i.rstrip('\n')
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1252, 880)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button = QtWidgets.QPushButton(self.centralwidget)
        self.Button.setGeometry(QtCore.QRect(370, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button.setFont(font)
        self.Button.setIconSize(QtCore.QSize(20, 20))
        self.Button.setObjectName("Button")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(370, 330, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_2.setFont(font)
        self.Button_2.setIconSize(QtCore.QSize(20, 20))
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(370, 410, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_3.setFont(font)
        self.Button_3.setIconSize(QtCore.QSize(20, 20))
        self.Button_3.setObjectName("Button_3")
        self.Button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_4.setGeometry(QtCore.QRect(370, 490, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_4.setFont(font)
        self.Button_4.setIconSize(QtCore.QSize(20, 20))
        self.Button_4.setObjectName("Button_4")
        self.Button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_5.setGeometry(QtCore.QRect(370, 570, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_5.setFont(font)
        self.Button_5.setIconSize(QtCore.QSize(20, 20))
        self.Button_5.setObjectName("Button_5")
        self.Button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_6.setGeometry(QtCore.QRect(460, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_6.setFont(font)
        self.Button_6.setIconSize(QtCore.QSize(20, 20))
        self.Button_6.setObjectName("Button_6")
        self.Button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_7.setGeometry(QtCore.QRect(460, 410, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_7.setFont(font)
        self.Button_7.setIconSize(QtCore.QSize(20, 20))
        self.Button_7.setObjectName("Button_7")
        self.Button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_8.setGeometry(QtCore.QRect(460, 330, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_8.setFont(font)
        self.Button_8.setIconSize(QtCore.QSize(20, 20))
        self.Button_8.setObjectName("Button_8")
        self.Button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_9.setGeometry(QtCore.QRect(460, 490, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_9.setFont(font)
        self.Button_9.setIconSize(QtCore.QSize(20, 20))
        self.Button_9.setObjectName("Button_9")
        self.Button_10 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_10.setGeometry(QtCore.QRect(460, 570, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_10.setFont(font)
        self.Button_10.setIconSize(QtCore.QSize(20, 20))
        self.Button_10.setObjectName("Button_10")
        self.Button_11 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_11.setEnabled(True)
        self.Button_11.setGeometry(QtCore.QRect(550, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_11.setFont(font)
        self.Button_11.setIconSize(QtCore.QSize(20, 20))
        self.Button_11.setObjectName("Button_11")
        self.Button_13 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_13.setGeometry(QtCore.QRect(550, 330, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_13.setFont(font)
        self.Button_13.setIconSize(QtCore.QSize(20, 20))
        self.Button_13.setObjectName("Button_13")
        self.Button_14 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_14.setGeometry(QtCore.QRect(550, 490, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_14.setFont(font)
        self.Button_14.setIconSize(QtCore.QSize(20, 20))
        self.Button_14.setObjectName("Button_14")
        self.Button_15 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_15.setGeometry(QtCore.QRect(550, 570, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_15.setFont(font)
        self.Button_15.setIconSize(QtCore.QSize(60, 78))
        self.Button_15.setObjectName("Button_15")
        self.Button_16 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_16.setGeometry(QtCore.QRect(640, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_16.setFont(font)
        self.Button_16.setIconSize(QtCore.QSize(20, 20))
        self.Button_16.setObjectName("Button_16")
        self.Button_17 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_17.setGeometry(QtCore.QRect(640, 410, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_17.setFont(font)
        self.Button_17.setIconSize(QtCore.QSize(20, 20))
        self.Button_17.setObjectName("Button_17")
        self.Button_18 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_18.setGeometry(QtCore.QRect(640, 330, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_18.setFont(font)
        self.Button_18.setIconSize(QtCore.QSize(20, 20))
        self.Button_18.setObjectName("Button_18")
        self.Button_19 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_19.setGeometry(QtCore.QRect(640, 490, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_19.setFont(font)
        self.Button_19.setIconSize(QtCore.QSize(20, 20))
        self.Button_19.setObjectName("Button_19")
        self.Button_20 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_20.setGeometry(QtCore.QRect(640, 570, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_20.setFont(font)
        self.Button_20.setIconSize(QtCore.QSize(20, 20))
        self.Button_20.setObjectName("Button_20")
        self.Button_21 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_21.setGeometry(QtCore.QRect(730, 250, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_21.setFont(font)
        self.Button_21.setIconSize(QtCore.QSize(20, 20))
        self.Button_21.setObjectName("Button_21")
        self.Button_22 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_22.setGeometry(QtCore.QRect(730, 410, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_22.setFont(font)
        self.Button_22.setIconSize(QtCore.QSize(20, 20))
        self.Button_22.setObjectName("Button_22")
        self.Button_23 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_23.setGeometry(QtCore.QRect(730, 330, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_23.setFont(font)
        self.Button_23.setIconSize(QtCore.QSize(20, 20))
        self.Button_23.setObjectName("Button_23")
        self.Button_24 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_24.setGeometry(QtCore.QRect(730, 490, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_24.setFont(font)
        self.Button_24.setIconSize(QtCore.QSize(20, 20))
        self.Button_24.setObjectName("Button_24")
        self.Button_12 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_12.setGeometry(QtCore.QRect(730, 570, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Button_12.setFont(font)
        self.Button_12.setIconSize(QtCore.QSize(20, 20))
        self.Button_12.setObjectName("Button_12")
        self.Picture = QtWidgets.QLabel(self.centralwidget)
        self.Picture.setGeometry(QtCore.QRect(550, 410, 81, 71))
        self.Picture.setText("")
        self.Picture.setObjectName("Picture")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(420, 160, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.Player = QtWidgets.QLabel(self.centralwidget)
        self.Player.setGeometry(QtCore.QRect(370, 80, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Player.setFont(font)
        self.Player.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Player.setObjectName("Player")
        self.Counter = QtWidgets.QLCDNumber(self.centralwidget)
        self.Counter.setGeometry(QtCore.QRect(480, 640, 241, 91))
        self.Counter.setObjectName("Counter")
        self.Dificulty = QtWidgets.QComboBox(self.centralwidget)
        self.Dificulty.setGeometry(QtCore.QRect(480, 20, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Dificulty.setFont(font)
        self.Dificulty.setObjectName("Dificulty")
        self.Dificulty.addItem("")
        self.Dificulty.addItem("")
        self.Dificulty.addItem("")
        self.help = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(10, 10, 191, 41))
        self.help.setObjectName("help")
        self.lider_dif = QtWidgets.QComboBox(self.centralwidget)
        self.lider_dif.setGeometry(QtCore.QRect(880, 60, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lider_dif.setFont(font)
        self.lider_dif.setObjectName("lider_dif")
        self.lider_dif.addItem("")
        self.lider_dif.addItem("")
        self.lider_dif.addItem("")
        self.Records = QtWidgets.QListWidget(self.centralwidget)
        self.Records.setGeometry(QtCore.QRect(860, 110, 371, 731))
        self.Records.setObjectName("Records")
        self.recs = QtWidgets.QLabel(self.centralwidget)
        self.recs.setGeometry(QtCore.QRect(970, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.recs.setFont(font)
        self.recs.setObjectName("recs")
        self.Podskazka = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Podskazka.setGeometry(QtCore.QRect(10, 60, 331, 781))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.Podskazka.setFont(font)
        self.Podskazka.setObjectName("Podskazka_2")
        self.BackPic = QtWidgets.QLabel(self.centralwidget)
        self.BackPic.setGeometry(QtCore.QRect(-30, -50, 1291, 921))
        self.BackPic.setText("")
        self.BackPic.setObjectName("BackPic")
        self.timer = QtWidgets.QLCDNumber(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(530, 750, 161, 51))
        self.timer.setObjectName("timer")
        self.BackPic.raise_()
        self.Button.raise_()
        self.Button_2.raise_()
        self.Button_3.raise_()
        self.Button_4.raise_()
        self.Button_5.raise_()
        self.Button_6.raise_()
        self.Button_7.raise_()
        self.Button_8.raise_()
        self.Button_9.raise_()
        self.Button_10.raise_()
        self.Button_11.raise_()
        self.Button_13.raise_()
        self.Button_14.raise_()
        self.Button_15.raise_()
        self.Button_16.raise_()
        self.Button_17.raise_()
        self.Button_18.raise_()
        self.Button_19.raise_()
        self.Button_20.raise_()
        self.Button_21.raise_()
        self.Button_22.raise_()
        self.Button_23.raise_()
        self.Button_24.raise_()
        self.Button_12.raise_()
        self.Picture.raise_()
        self.StartButton.raise_()
        self.Player.raise_()
        self.Counter.raise_()
        self.Dificulty.raise_()
        self.help.raise_()
        self.lider_dif.raise_()
        self.Records.raise_()
        self.recs.raise_()
        self.Podskazka.raise_()
        self.timer.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1252, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Таблица Шульте"))
        self.Button.setText(_translate("MainWindow", "1"))
        self.Button_2.setText(_translate("MainWindow", "6"))
        self.Button_3.setText(_translate("MainWindow", "11"))
        self.Button_4.setText(_translate("MainWindow", "15"))
        self.Button_5.setText(_translate("MainWindow", "20"))
        self.Button_6.setText(_translate("MainWindow", "2"))
        self.Button_7.setText(_translate("MainWindow", "12"))
        self.Button_8.setText(_translate("MainWindow", "7"))
        self.Button_9.setText(_translate("MainWindow", "16"))
        self.Button_10.setText(_translate("MainWindow", "21"))
        self.Button_11.setText(_translate("MainWindow", "3"))
        self.Button_13.setText(_translate("MainWindow", "8"))
        self.Button_14.setText(_translate("MainWindow", "17"))
        self.Button_15.setText(_translate("MainWindow", "22"))
        self.Button_16.setText(_translate("MainWindow", "4"))
        self.Button_17.setText(_translate("MainWindow", "13"))
        self.Button_18.setText(_translate("MainWindow", "9"))
        self.Button_19.setText(_translate("MainWindow", "18"))
        self.Button_20.setText(_translate("MainWindow", "23"))
        self.Button_21.setText(_translate("MainWindow", "5"))
        self.Button_22.setText(_translate("MainWindow", "14"))
        self.Button_23.setText(_translate("MainWindow", "10"))
        self.Button_24.setText(_translate("MainWindow", "19"))
        self.Button_12.setText(_translate("MainWindow", "24"))
        self.StartButton.setText(_translate("MainWindow", "Начать"))
        self.Player.setText(_translate("MainWindow", "Начните игру"))
        self.Dificulty.setItemText(0, _translate("MainWindow", "Легко"))
        self.Dificulty.setItemText(1, _translate("MainWindow", "Средне"))
        self.Dificulty.setItemText(2, _translate("MainWindow", "Сложно"))
        self.help.setText(_translate("MainWindow", "Показать подсказку?"))
        self.lider_dif.setItemText(0, _translate("MainWindow", "Легко"))
        self.lider_dif.setItemText(1, _translate("MainWindow", "Средне"))
        self.lider_dif.setItemText(2, _translate("MainWindow", "Сложно"))
        self.recs.setText(_translate("MainWindow", "Рекорды"))
        self.Podskazka.setPlainText(_translate("MainWindow", text))

